# This file configures the analyzer for Dart code.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    non_constant_identifier_names: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # Desactivadas
    file_names: false
    avoid_print: false
    unawaited_futures: false
    # Activadas
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    valid_regexps: true
